#!/usr/bin/env python2.7
import sys
port_number = int(sys.argv[1])
msg404 = "HTTP/1.1 404 Not Found\r\nContent-type: text/html\r\nContent-length: 135\r\n\r\n<html><head><title>Not Found</title></head><body>\r\nSorry, the object you requested was not found.\r\n</body><html>\r\n\r\n"
from socket import *
s = socket()
s.connect(("127.0.0.1",port_number))
counter_request_number =0
while True:
	msg = ""
	receiveMsg = True
	while(receiveMsg == True):
		msg = msg + s.recv(1024)
		if (msg.find("\r\n\r\n") != -1):
			break;
	first_row = msg.split('\n',1)[0]
	send_msg = ""
	if first_row.find("GET /counter") >= 0 :
		counter_request_number +=1
		counter_str = str(counter_request_number)
		send_msg = "HTTP/1.0 200 OK\r\nContent-Type: text/html\r\nContent-Length: "
		send_msg = send_msg + `len(counter_str)` +"\r\n\r\n"+counter_str+"\r\n\r\n"
	else: 
		send_msg = msg404
	s.send(send_msg)
s.close()
